name: test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  plan:
    name: plan
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.plan.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3

      - uses: MOZGIII/action-plan@master
        id: plan
        with:
          plan-file: .github/action-plan.ts

  action:
    needs:
      - plan
    strategy:
      matrix: ${{ fromJson(needs.plan.outputs.matrix) }}
      fail-fast: false
    name: ${{ matrix.commands.name }}
    runs-on: ubuntu-latest

    steps:
      - run: ${{ matrix.commands.command }}
